export const availableTimeSlots=[5,15,30,45,60,90,120];
export const hours = ["00","01","02","03","04","05","06","07","08","09","10","11","12","13","14","15","16","17","18","19","20","21","22","23"]
export const API_URL = "http://localhost:8080/";
export const MANAGER_TYPE="manager";
export const MANAGER_TYPE_ALL="manager/all"
export const LAB_TYPE="lab"; 
export const LAB_TYPE_ALL="lab/all"
export const BOOKING_TYPE="booking";
export const BOOKING_TYPE_ALL="booking/all";
export const BOOKING_TYPE_MY="booking/my";
export const LAB_BY_MANAGER="lab/manager/";
export const USER_TYPE="user";
export const USER_TYPE_ALL="user/all";
export const LOGIN = "auth/login";
export const SIGNUP = "auth/signup";
export const LOGOUT = "auth/logout";
export const DELETE = "/delete/";
export const SAVE = "/save";
export const BOOKING_DISABLED = "booking/disabled/";